version: "3"
services:
  lidarr-deemix:
    image: ghcr.io/ad-on-is/lidarr-deemix
    container_name: lidarr-deemix
    ports:
      - 8080:8080 # optional, only if you want to expose the port to the host
    environment:
      - DEEMIX_ARL=xxxx
